version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
